#!/bin/bash
# Builds the arXiv submission tarball and then compiles it in a clean directory, because a
# package that only builds inside the working tree is the standard way to fail an arXiv upload.
#
# arXiv runs its own TeX Live over whatever is in the tarball. This paper needs no bibtex pass --
# the bibliography is an inline thebibliography -- so the tarball is self-contained once the tex,
# the tables/ and the figures actually referenced are included.
#
# Usage: bash scripts/55_build_arxiv_package.sh
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=dist/arxiv
STAGE="$OUT/src"
rm -rf "$OUT"
mkdir -p "$STAGE/tables" "$STAGE/figures"

cp paper/paper.tex "$STAGE/"
cp paper/tables/*.tex "$STAGE/tables/"

# Only the figures the document actually includes, in the format it asks for.
python3 - <<'PY'
import re, shutil
from pathlib import Path
tex = Path("paper/paper.tex").read_text()
wanted = set(re.findall(r'\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}', tex))
for w in sorted(wanted):
    src = Path("paper") / w
    if not src.suffix:
        for ext in (".pdf", ".png"):
            if (Path("paper") / (w + ext)).exists():
                src = Path("paper") / (w + ext)
                break
    dst = Path("dist/arxiv/src") / src.relative_to("paper")
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    print(f"figure: {src} -> {dst}")
PY

# Compile in a copy that has nothing else in it, which is what arXiv sees.
CLEAN=$(mktemp -d)
cp -R "$STAGE/." "$CLEAN/"
( cd "$CLEAN" && tectonic -X compile paper.tex --keep-logs >/dev/null 2>&1 )
PAGES=$(grep -oE "Output written on paper.xdv \([0-9]+ pages" "$CLEAN/paper.log" | grep -oE "[0-9]+")
UNDEF=$(grep -ciE "undefined (control sequence|reference)|multiply.defined" "$CLEAN/paper.log" || true)
echo "isolated build: ${PAGES} pages, ${UNDEF} undefined-reference warnings"
[ "$UNDEF" = "0" ] || { echo "FAIL: unresolved references in the isolated build"; exit 1; }
cp "$CLEAN/paper.pdf" "$OUT/paper.pdf"
rm -rf "$CLEAN"

( cd "$STAGE" && tar --disable-copyfile -czf ../arxiv-submission.tar.gz . )
echo "wrote $OUT/arxiv-submission.tar.gz ($(du -h "$OUT/arxiv-submission.tar.gz" | cut -f1))"
tar -tzf "$OUT/arxiv-submission.tar.gz" | sed 's/^/  /'

# The metadata is generated here rather than kept by hand so the comments field cannot drift from
# the artifact it describes: the page count comes from the isolated build above, the figure and
# table counts from the document itself.
PAGES="$PAGES" python3 - <<'PY'
import os, re, glob
from pathlib import Path
tex = Path("paper/paper.tex").read_text()
figs = len(re.findall(r'\\begin\{figure', tex))
tables = len(re.findall(r'\\begin\{table', tex)) + sum(
    len(re.findall(r'\\begin\{table', Path(f).read_text()))
    for f in glob.glob("paper/tables/*.tex")
    if f"tables/{Path(f).stem}" in tex)
abstract = (
"A classifier reading raw weights of independently fitted implicit neural representations (INRs) "
"performs near chance; reading weights fitted from a shared initialization it nearly matches a "
"pixel model. This gap is usually attributed to parameter symmetry, without measurement. We "
"characterize the group generated by the function-preserving transformations of sine networks: "
"each hidden neuron carries an infinite dihedral action D_inf whose phase component is affine, "
"outside the monomial-matrix actions previous classifications cover, and a layer carries D_inf wr "
"S_n, which for generic one-hidden-layer networks we prove exhausts functional equivalence. Exact "
"reframing recovers 63%, 66% and 32% of the gap, but that is relative to the reader and its "
"training algorithm rather than a causal share, so we also intervene: random group "
"transformations applied to a shared-initialization corpus, leaving every realized function "
"unchanged, cost 79 of the 80 points. Group scatter is therefore sufficient to reproduce almost "
"the whole degradation, though this does not identify what fraction of the natural gap symmetry "
"mediates. Bias phasors then reduce the winding to a parity, leaving a finite grading a network "
"preserves layer by layer, and we prove the resulting reader on raw parameters is exactly "
"invariant. On the standard MNIST-INR benchmark it reaches 93.1%, ahead of DWSNets, both NFN "
"variants and NG-GNN and 3.5 points behind ScaleGMN: a competitive reader, not a leading one. "
"That benchmark is independently initialized by our own measure, so the published leaderboard is "
"already set in the hard regime. Querying the same INR at 64 learned coordinates remains more "
"accurate than every weight-space pipeline we built, and about 100x cheaper.")
assert len(abstract) <= 1920, f"abstract is {len(abstract)} chars, over arXiv's 1920 limit"
Path("dist/arxiv/METADATA.txt").write_text(f"""arXiv submission metadata -- generated by scripts/55_build_arxiv_package.sh, do not edit by hand
=================================================================================================

Title:
  How Much of the Weight-Space Perception Gap Is Symmetry?
  Evidence from Sine Networks

Authors:
  Mehmet Demir Guven (Department of Computer Science, ETH Zurich)

Primary category:
  cs.LG

Cross-lists:
  stat.ML   -- the pre-registrations, interval scoring and calibration audit
  cs.CV     -- implicit neural representations; the corpora are image INRs

Comments field:
  {os.environ['PAGES']} pages, {figs} figures, {tables} tables. Code, corpus generators, all
  pre-registrations and the full prediction ledger (hits and misses):
  https://github.com/ITheClixs/project-siren-gap

License:
  CC BY 4.0 (repository code is MIT)

MSC / ACM (optional):
  MSC 68T07, 20C35 ; ACM I.2.6, I.5.1

Abstract ({len(abstract)} chars; arXiv's limit is 1920 and applies to this field, not to the PDF):
{abstract}

Notes for the upload
--------------------
* Upload dist/arxiv/arxiv-submission.tar.gz. It holds paper.tex, tables/ and only the figures the
  document includes. No .bib is needed -- the bibliography is an inline thebibliography, so
  arXiv's TeX Live compiles it in one pass.
* This script compiles that exact tarball in a clean directory and fails if a reference is
  unresolved, so what is uploaded is what was verified.
* Do not attach the corpora as ancillary files: they regenerate from the committed generator, and
  the repository link above is the data-availability statement.
""")
print(f"wrote dist/arxiv/METADATA.txt ({figs} figures, {tables} tables, abstract {len(abstract)} chars)")
PY
