#!/usr/bin/env python3
"""Audit every pre-registration against the git commit that froze it.

A ledger row records the first 16 hex characters of the sha256 of the frozen file. Several files
later gained appended deviation logs or amendments, so their current hash no longer matches. This
walks each file's git history, finds the version whose hash the ledger records, saves that version
under docs/prereg/frozen/, and writes docs/prereg/AUDIT.md: for each registration, its ledger hash,
the commit that froze it and its date, whether the file has changed since, and the date of the first
commit touching the study's results directory, which is the external evidence that registration
came before results. Studies registered by commit without ledger rows are listed as such.

    python3 scripts/85_prereg_audit.py
"""

from __future__ import annotations

import csv
import hashlib
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PREREG = ROOT / "docs" / "prereg"
FROZEN = PREREG / "frozen"


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True).stdout


def h16(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:16]


def versions(rel: str) -> list[tuple[str, str, str]]:
    """(commit, ISO date, hash) for every committed version, oldest first."""
    out = []
    for line in git("log", "--format=%H %cI", "--follow", "--", rel).splitlines()[::-1]:
        commit, date = line.split()
        blob = subprocess.run(["git", "show", f"{commit}:{rel}"], cwd=ROOT, capture_output=True).stdout
        if blob:
            out.append((commit, date, h16(blob)))
    return out


def first_results_commit(stem: str) -> str:
    base = stem.split("-")[0].lower()
    path = ROOT / "results" / base
    if not path.is_dir():
        return "n/a"
    dates = git("log", "--format=%cI", "--reverse", "--", f"results/{base}").split()
    return dates[0][:16] if dates else "n/a"


def main() -> None:
    ledger: dict[str, str] = {}
    with open(ROOT / "docs" / "PREDICTION_LEDGER.csv") as f:
        for row in csv.reader(f):
            if len(row) >= 7 and len(row[-1]) == 16:
                ledger.setdefault(row[-1], row[0])
    FROZEN.mkdir(exist_ok=True)
    rows, matched = [], set()
    for path in sorted(PREREG.glob("*.md")):
        if path.name == "AUDIT.md":
            continue
        rel = str(path.relative_to(ROOT))
        vs = versions(rel)
        current = h16(path.read_bytes())
        hit = next(((c, d, h) for c, d, h in vs if h in ledger), None)
        if hit:
            matched.add(hit[2])
            same = hit[2] == current
            if not same:
                blob = subprocess.run(["git", "show", f"{hit[0]}:{rel}"], cwd=ROOT,
                                      capture_output=True).stdout
                (FROZEN / f"{path.stem}@{hit[0][:7]}.md").write_bytes(blob)
            status = "unchanged since frozen" if same else f"amended later; frozen copy saved"
            rows.append((path.stem, hit[2], f"{hit[0][:7]} ({hit[1][:16]})", status,
                         first_results_commit(path.stem)))
        else:
            first = vs[0] if vs else ("?", "?", "?")
            rows.append((path.stem, "no ledger row", f"{first[0][:7]} ({first[1][:16]})",
                         "registered by commit only", first_results_commit(path.stem)))
    orphans = sorted(set(ledger) - matched)
    # Early gates were frozen in design documents rather than in docs/prereg; look there too.
    located: dict[str, tuple[str, str, str]] = {}
    docs = sorted({f for f in git("log", "--all", "--format=", "--name-only", "--", "docs").split()
                   if f.endswith(".md") and not f.startswith("docs/prereg/")})
    for rel in docs:
        for line in git("log", "--all", "--format=%H %cI", "--", rel).splitlines():
            commit, date = line.split()
            blob = subprocess.run(["git", "show", f"{commit}:{rel}"], cwd=ROOT, capture_output=True).stdout
            h = h16(blob)
            if h in orphans and h not in located:
                located[h] = (rel, commit[:7], date[:16])
    lines = [
        "# Pre-registration audit", "",
        "Generated by `scripts/85_prereg_audit.py`. The ledger hash is the first 16 hex characters of",
        "the sha256 of the frozen file; the commit is the one whose version of the file has that hash.",
        "For files amended after freezing, the frozen version is saved in `frozen/`. The last column is",
        "the first commit touching the study's results directory, where one exists under that name.", "",
        "| registration | ledger hash | frozen at commit (date) | status | first results commit |",
        "|---|---|---|---|---|",
    ] + [f"| {a} | `{b}` | {c} | {d} | {e} |" for a, b, c, d, e in rows]
    lines += ["", "Ledger hashes of early gates frozen outside `docs/prereg` (design documents):", ""]
    lines += [f"- `{h}` (ledger date {ledger[h]}): `{located[h][0]}` at {located[h][1]} ({located[h][2]})"
              for h in orphans if h in located]
    missing = [h for h in orphans if h not in located]
    lines += ["", f"Ledger hashes matching no committed document: {len(missing)}"]
    lines += [f"- `{h}` (ledger date {ledger[h]})" for h in missing]
    (PREREG / "AUDIT.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
